# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(519, 432)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.ok_btn = QtWidgets.QPushButton(Dialog)
        self.ok_btn.setGeometry(QtCore.QRect(200, 390, 111, 23))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok_btn.sizePolicy().hasHeightForWidth())
        self.ok_btn.setSizePolicy(sizePolicy)
        self.ok_btn.setObjectName("ok_btn")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label.setObjectName("label")
        self.sort_name = QtWidgets.QLineEdit(Dialog)
        self.sort_name.setGeometry(QtCore.QRect(120, 30, 321, 20))
        self.sort_name.setObjectName("sort_name")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 200, 91, 16))
        self.label_2.setObjectName("label_2")
        self.taste = QtWidgets.QPlainTextEdit(Dialog)
        self.taste.setGeometry(QtCore.QRect(120, 140, 321, 151))
        self.taste.setObjectName("taste")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 121, 16))
        self.label_3.setObjectName("label_3")
        self.roast = QtWidgets.QComboBox(Dialog)
        self.roast.setGeometry(QtCore.QRect(120, 70, 321, 22))
        self.roast.setObjectName("roast")
        self.is_powder = QtWidgets.QComboBox(Dialog)
        self.is_powder.setGeometry(QtCore.QRect(120, 110, 321, 22))
        self.is_powder.setObjectName("is_powder")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 110, 121, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 310, 121, 16))
        self.label_5.setObjectName("label_5")
        self.price = QtWidgets.QSpinBox(Dialog)
        self.price.setGeometry(QtCore.QRect(120, 310, 321, 22))
        self.price.setMinimum(1)
        self.price.setMaximum(10000)
        self.price.setObjectName("price")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 350, 121, 16))
        self.label_6.setObjectName("label_6")
        self.volume = QtWidgets.QSpinBox(Dialog)
        self.volume.setGeometry(QtCore.QRect(120, 350, 321, 22))
        self.volume.setMinimum(1)
        self.volume.setMaximum(10000)
        self.volume.setObjectName("volume")
        self.error_lbl = QtWidgets.QLabel(Dialog)
        self.error_lbl.setGeometry(QtCore.QRect(10, 10, 451, 16))
        self.error_lbl.setText("")
        self.error_lbl.setObjectName("error_lbl")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавить/редактировать сорт"))
        self.ok_btn.setText(_translate("Dialog", "Подтвердить"))
        self.label.setText(_translate("Dialog", "Название сорта"))
        self.label_2.setText(_translate("Dialog", "Вкус"))
        self.label_3.setText(_translate("Dialog", "Степень прожарки"))
        self.label_4.setText(_translate("Dialog", "Молотый/в зёрнах"))
        self.label_5.setText(_translate("Dialog", "Цена"))
        self.label_6.setText(_translate("Dialog", "Объём упаковки"))
